environment=test

env.test.baseUrl=https://reqres.in/api
env.test.timeout=30000
env.test.connectTimeout=10000
env.test.readTimeout=30000
env.test.apiKey=pro_9deaf54c789fc909d0f0bc58eba4fcbf2ebb6c601f19e7145f1c602ff209cf81



env.dev.baseUrl=https://dev-api.example.com/api
env.dev.timeout=30000
env.dev.connectTimeout=10000

env.uat.baseUrl=https://uat-api.example.com/api
env.uat.timeout=30000
env.uat.connectTimeout=10000

env.prod.baseUrl=https://api.example.com/api
env.prod.timeout=30000
env.prod.connectTimeout=10000